<?php
/**
 * Autogenerated file.
 */

declare(strict_types=1);

namespace TelegramSDK\BotKit;

use TelegramSDK\BotAPI\Telegram\TelegramResponse;

trait MethodsTrait
{
    /**
     * A simple method for testing your bot's authentication token.
     * Requires no parameters.
     * Returns basic information about the bot in form of a User object.
     */
    public function getMe(): TelegramResponse
    {
        return parent::getMe(Helpers::array_filter([]));
    }

    /**
     * Use this method to log out from the cloud Bot API server before launching the bot locally.
     * You must log out the bot before running it locally, otherwise there is no guarantee that the bot will receive updates.
     * After a successful call, you can immediately log in on a local server, but will not be able to log in back to the cloud Bot API server for 10 minutes.
     * Returns True on success.
     * Requires no parameters.
     */
    public function logOut(): TelegramResponse
    {
        return parent::logOut(Helpers::array_filter([]));
    }

    /**
     * Use this method to close the bot instance before moving it from one local server to another.
     * You need to delete the webhook before calling this method to ensure that the bot isn't launched again after server restart.
     * The method will return error 429 in the first 10 minutes after the bot is launched.
     * Returns True on success.
     * Requires no parameters.
     */
    public function close(): TelegramResponse
    {
        return parent::close(Helpers::array_filter([]));
    }

    /**
     * Use this method to send text messages.
     * On success, the sent Message is returned.
     */
    public function sendMessage($chat_id, $text, $business_connection_id = null, $message_thread_id = null, $parse_mode = null, $entities = null, $link_preview_options = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendMessage(Helpers::array_filter(['chat_id' => $chat_id, 'text' => $text, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'parse_mode' => $parse_mode, 'entities' => $entities, 'link_preview_options' => $link_preview_options, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to forward messages of any kind.
     * Service messages and messages with protected content can't be forwarded.
     * On success, the sent Message is returned.
     */
    public function forwardMessage($chat_id, $from_chat_id, $message_id, $message_thread_id = null, $disable_notification = null, $protect_content = null): TelegramResponse
    {
        return parent::forwardMessage(Helpers::array_filter(['chat_id' => $chat_id, 'from_chat_id' => $from_chat_id, 'message_id' => $message_id, 'message_thread_id' => $message_thread_id, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content]));
    }

    /**
     * Use this method to forward multiple messages of any kind.
     * If some of the specified messages can't be found or forwarded, they are skipped.
     * Service messages and messages with protected content can't be forwarded.
     * Album grouping is kept for forwarded messages.
     * On success, an array of MessageId of the sent messages is returned.
     */
    public function forwardMessages($chat_id, $from_chat_id, $message_ids, $message_thread_id = null, $disable_notification = null, $protect_content = null): TelegramResponse
    {
        return parent::forwardMessages(Helpers::array_filter(['chat_id' => $chat_id, 'from_chat_id' => $from_chat_id, 'message_ids' => $message_ids, 'message_thread_id' => $message_thread_id, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content]));
    }

    /**
     * Use this method to copy messages of any kind.
     * Service messages, paid media messages, giveaway messages, giveaway winners messages, and invoice messages can't be copied.
     * A quiz poll can be copied only if the value of the field correct_option_id is known to the bot.
     * The method is analogous to the method forwardMessage, but the copied message doesn't have a link to the original message.
     * Returns the MessageId of the sent message on success.
     */
    public function copyMessage($chat_id, $from_chat_id, $message_id, $message_thread_id = null, $caption = null, $parse_mode = null, $caption_entities = null, $show_caption_above_media = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::copyMessage(Helpers::array_filter(['chat_id' => $chat_id, 'from_chat_id' => $from_chat_id, 'message_id' => $message_id, 'message_thread_id' => $message_thread_id, 'caption' => $caption, 'parse_mode' => $parse_mode, 'caption_entities' => $caption_entities, 'show_caption_above_media' => $show_caption_above_media, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to copy messages of any kind.
     * If some of the specified messages can't be found or copied, they are skipped.
     * Service messages, paid media messages, giveaway messages, giveaway winners messages, and invoice messages can't be copied.
     * A quiz poll can be copied only if the value of the field correct_option_id is known to the bot.
     * The method is analogous to the method forwardMessages, but the copied messages don't have a link to the original message.
     * Album grouping is kept for copied messages.
     * On success, an array of MessageId of the sent messages is returned.
     */
    public function copyMessages($chat_id, $from_chat_id, $message_ids, $message_thread_id = null, $disable_notification = null, $protect_content = null, $remove_caption = null): TelegramResponse
    {
        return parent::copyMessages(Helpers::array_filter(['chat_id' => $chat_id, 'from_chat_id' => $from_chat_id, 'message_ids' => $message_ids, 'message_thread_id' => $message_thread_id, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'remove_caption' => $remove_caption]));
    }

    /**
     * Use this method to send photos.
     * On success, the sent Message is returned.
     */
    public function sendPhoto($chat_id, $photo, $business_connection_id = null, $message_thread_id = null, $caption = null, $parse_mode = null, $caption_entities = null, $show_caption_above_media = null, $has_spoiler = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendPhoto(Helpers::array_filter(['chat_id' => $chat_id, 'photo' => $photo, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'caption' => $caption, 'parse_mode' => $parse_mode, 'caption_entities' => $caption_entities, 'show_caption_above_media' => $show_caption_above_media, 'has_spoiler' => $has_spoiler, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to send audio files, if you want Telegram clients to display them in the music player.
     * Your audio must be in the .MP3 or .M4A format.
     * On success, the sent Message is returned.
     * Bots can currently send audio files of up to 50 MB in size, this limit may be changed in the future.
     */
    public function sendAudio(): TelegramResponse
    {
        return parent::sendAudio(Helpers::array_filter([]));
    }

    /**
     * Use this method to send general files.
     * On success, the sent Message is returned.
     * Bots can currently send files of any type of up to 50 MB in size, this limit may be changed in the future.
     */
    public function sendDocument($chat_id, $document, $business_connection_id = null, $message_thread_id = null, $thumbnail = null, $caption = null, $parse_mode = null, $caption_entities = null, $disable_content_type_detection = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendDocument(Helpers::array_filter(['chat_id' => $chat_id, 'document' => $document, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'thumbnail' => $thumbnail, 'caption' => $caption, 'parse_mode' => $parse_mode, 'caption_entities' => $caption_entities, 'disable_content_type_detection' => $disable_content_type_detection, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to send video files, Telegram clients support MPEG4 videos (other formats may be sent as Document).
     * On success, the sent Message is returned.
     * Bots can currently send video files of up to 50 MB in size, this limit may be changed in the future.
     */
    public function sendVideo($chat_id, $video, $business_connection_id = null, $message_thread_id = null, $duration = null, $width = null, $height = null, $thumbnail = null, $caption = null, $parse_mode = null, $caption_entities = null, $show_caption_above_media = null, $has_spoiler = null, $supports_streaming = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendVideo(Helpers::array_filter(['chat_id' => $chat_id, 'video' => $video, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'duration' => $duration, 'width' => $width, 'height' => $height, 'thumbnail' => $thumbnail, 'caption' => $caption, 'parse_mode' => $parse_mode, 'caption_entities' => $caption_entities, 'show_caption_above_media' => $show_caption_above_media, 'has_spoiler' => $has_spoiler, 'supports_streaming' => $supports_streaming, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to send animation files (GIF or H.264/MPEG-4 AVC video without sound).
     * On success, the sent Message is returned.
     * Bots can currently send animation files of up to 50 MB in size, this limit may be changed in the future.
     */
    public function sendAnimation($chat_id, $animation, $business_connection_id = null, $message_thread_id = null, $duration = null, $width = null, $height = null, $thumbnail = null, $caption = null, $parse_mode = null, $caption_entities = null, $show_caption_above_media = null, $has_spoiler = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendAnimation(Helpers::array_filter(['chat_id' => $chat_id, 'animation' => $animation, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'duration' => $duration, 'width' => $width, 'height' => $height, 'thumbnail' => $thumbnail, 'caption' => $caption, 'parse_mode' => $parse_mode, 'caption_entities' => $caption_entities, 'show_caption_above_media' => $show_caption_above_media, 'has_spoiler' => $has_spoiler, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to send audio files, if you want Telegram clients to display the file as a playable voice message.
     * For this to work, your audio must be in an .OGG file encoded with OPUS, or in .MP3 format, or in .M4A format (other formats may be sent as Audio or Document).
     * On success, the sent Message is returned.
     * Bots can currently send voice messages of up to 50 MB in size, this limit may be changed in the future.
     */
    public function sendVoice($chat_id, $voice, $business_connection_id = null, $message_thread_id = null, $caption = null, $parse_mode = null, $caption_entities = null, $duration = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendVoice(Helpers::array_filter(['chat_id' => $chat_id, 'voice' => $voice, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'caption' => $caption, 'parse_mode' => $parse_mode, 'caption_entities' => $caption_entities, 'duration' => $duration, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * As of v.4.0, Telegram clients support rounded square MPEG4 videos of up to 1 minute long.
     * Use this method to send video messages.
     * On success, the sent Message is returned.
     */
    public function sendVideoNote($chat_id, $video_note, $business_connection_id = null, $message_thread_id = null, $duration = null, $length = null, $thumbnail = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendVideoNote(Helpers::array_filter(['chat_id' => $chat_id, 'video_note' => $video_note, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'duration' => $duration, 'length' => $length, 'thumbnail' => $thumbnail, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to send paid media.
     * On success, the sent Message is returned.
     */
    public function sendPaidMedia($chat_id, $star_count, $media, $business_connection_id = null, $payload = null, $caption = null, $parse_mode = null, $caption_entities = null, $show_caption_above_media = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendPaidMedia(Helpers::array_filter(['chat_id' => $chat_id, 'star_count' => $star_count, 'media' => $media, 'business_connection_id' => $business_connection_id, 'payload' => $payload, 'caption' => $caption, 'parse_mode' => $parse_mode, 'caption_entities' => $caption_entities, 'show_caption_above_media' => $show_caption_above_media, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to send a group of photos, videos, documents or audios as an album.
     * Documents and audio files can be only grouped in an album with messages of the same type.
     * On success, an array of Messages that were sent is returned.
     */
    public function sendMediaGroup($chat_id, $media, $business_connection_id = null, $message_thread_id = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null): TelegramResponse
    {
        return parent::sendMediaGroup(Helpers::array_filter(['chat_id' => $chat_id, 'media' => $media, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters]));
    }

    /**
     * Use this method to send point on the map.
     * On success, the sent Message is returned.
     */
    public function sendLocation($chat_id, $latitude, $longitude, $business_connection_id = null, $message_thread_id = null, $horizontal_accuracy = null, $live_period = null, $heading = null, $proximity_alert_radius = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendLocation(Helpers::array_filter(['chat_id' => $chat_id, 'latitude' => $latitude, 'longitude' => $longitude, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'horizontal_accuracy' => $horizontal_accuracy, 'live_period' => $live_period, 'heading' => $heading, 'proximity_alert_radius' => $proximity_alert_radius, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to send information about a venue.
     * On success, the sent Message is returned.
     */
    public function sendVenue($chat_id, $latitude, $longitude, $title, $address, $business_connection_id = null, $message_thread_id = null, $foursquare_id = null, $foursquare_type = null, $google_place_id = null, $google_place_type = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendVenue(Helpers::array_filter(['chat_id' => $chat_id, 'latitude' => $latitude, 'longitude' => $longitude, 'title' => $title, 'address' => $address, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'foursquare_id' => $foursquare_id, 'foursquare_type' => $foursquare_type, 'google_place_id' => $google_place_id, 'google_place_type' => $google_place_type, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to send phone contacts.
     * On success, the sent Message is returned.
     */
    public function sendContact($chat_id, $phone_number, $first_name, $business_connection_id = null, $message_thread_id = null, $last_name = null, $vcard = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendContact(Helpers::array_filter(['chat_id' => $chat_id, 'phone_number' => $phone_number, 'first_name' => $first_name, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'last_name' => $last_name, 'vcard' => $vcard, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to send a native poll.
     * On success, the sent Message is returned.
     */
    public function sendPoll($chat_id, $question, $options, $business_connection_id = null, $message_thread_id = null, $question_parse_mode = null, $question_entities = null, $is_anonymous = null, $type = null, $allows_multiple_answers = null, $correct_option_id = null, $explanation = null, $explanation_parse_mode = null, $explanation_entities = null, $open_period = null, $close_date = null, $is_closed = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendPoll(Helpers::array_filter(['chat_id' => $chat_id, 'question' => $question, 'options' => $options, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'question_parse_mode' => $question_parse_mode, 'question_entities' => $question_entities, 'is_anonymous' => $is_anonymous, 'type' => $type, 'allows_multiple_answers' => $allows_multiple_answers, 'correct_option_id' => $correct_option_id, 'explanation' => $explanation, 'explanation_parse_mode' => $explanation_parse_mode, 'explanation_entities' => $explanation_entities, 'open_period' => $open_period, 'close_date' => $close_date, 'is_closed' => $is_closed, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to send an animated emoji that will display a random value.
     * On success, the sent Message is returned.
     */
    public function sendDice($chat_id, $business_connection_id = null, $message_thread_id = null, $emoji = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendDice(Helpers::array_filter(['chat_id' => $chat_id, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'emoji' => $emoji, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method when you need to tell the user that something is happening on the bot's side.
     * The status is set for 5 seconds or less (when a message arrives from your bot, Telegram clients clear its typing status).
     * Returns True on success.
     */
    public function sendChatAction(): TelegramResponse
    {
        return parent::sendChatAction(Helpers::array_filter([]));
    }

    /**
     * Use this method to change the chosen reactions on a message.
     * Service messages can't be reacted to.
     * Automatically forwarded messages from a channel to its discussion group have the same available reactions as messages in the channel.
     * Bots can't use paid reactions.
     * Returns True on success.
     */
    public function setMessageReaction($chat_id, $message_id, $reaction = null, $is_big = null): TelegramResponse
    {
        return parent::setMessageReaction(Helpers::array_filter(['chat_id' => $chat_id, 'message_id' => $message_id, 'reaction' => $reaction, 'is_big' => $is_big]));
    }

    /**
     * Use this method to get a list of profile pictures for a user.
     * Returns a UserProfilePhotos object.
     */
    public function getUserProfilePhotos($user_id, $offset = null, $limit = null): TelegramResponse
    {
        return parent::getUserProfilePhotos(Helpers::array_filter(['user_id' => $user_id, 'offset' => $offset, 'limit' => $limit]));
    }

    /**
     * Use this method to get basic information about a file and prepare it for downloading.
     * For the moment, bots can download files of up to 20MB in size.
     * On success, a File object is returned.
     * The file can then be downloaded via the link https://api.telegram.org/file/bot<token>/<file_path>, where <file_path> is taken from the response.
     * It is guaranteed that the link will be valid for at least 1 hour.
     * When the link expires, a new one can be requested by calling getFile again.
     */
    public function getFile($file_id): TelegramResponse
    {
        return parent::getFile(Helpers::array_filter(['file_id' => $file_id]));
    }

    /**
     * Use this method to ban a user in a group, a supergroup or a channel.
     * In the case of supergroups and channels, the user will not be able to return to the chat on their own using invite links, etc., unless unbanned first.
     * The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights.
     * Returns True on success.
     */
    public function banChatMember($chat_id, $user_id, $until_date = null, $revoke_messages = null): TelegramResponse
    {
        return parent::banChatMember(Helpers::array_filter(['chat_id' => $chat_id, 'user_id' => $user_id, 'until_date' => $until_date, 'revoke_messages' => $revoke_messages]));
    }

    /**
     * Use this method to unban a previously banned user in a supergroup or channel.
     * The user will not return to the group or channel automatically, but will be able to join via link, etc.
     * The bot must be an administrator for this to work.
     * By default, this method guarantees that after the call the user is not a member of the chat, but will be able to join it.
     * So if the user is a member of the chat they will also be removed from the chat.
     * If you don't want this, use the parameter only_if_banned.
     * Returns True on success.
     */
    public function unbanChatMember($chat_id, $user_id, $only_if_banned = null): TelegramResponse
    {
        return parent::unbanChatMember(Helpers::array_filter(['chat_id' => $chat_id, 'user_id' => $user_id, 'only_if_banned' => $only_if_banned]));
    }

    /**
     * Use this method to restrict a user in a supergroup.
     * The bot must be an administrator in the supergroup for this to work and must have the appropriate administrator rights.
     * Pass True for all permissions to lift restrictions from a user.
     * Returns True on success.
     */
    public function restrictChatMember($chat_id, $user_id, $permissions, $use_independent_chat_permissions = null, $until_date = null): TelegramResponse
    {
        return parent::restrictChatMember(Helpers::array_filter(['chat_id' => $chat_id, 'user_id' => $user_id, 'permissions' => $permissions, 'use_independent_chat_permissions' => $use_independent_chat_permissions, 'until_date' => $until_date]));
    }

    /**
     * Use this method to promote or demote a user in a supergroup or a channel.
     * The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights.
     * Pass False for all boolean parameters to demote a user.
     * Returns True on success.
     */
    public function promoteChatMember($chat_id, $user_id, $is_anonymous = null, $can_manage_chat = null, $can_delete_messages = null, $can_manage_video_chats = null, $can_restrict_members = null, $can_promote_members = null, $can_change_info = null, $can_invite_users = null, $can_post_stories = null, $can_edit_stories = null, $can_delete_stories = null, $can_post_messages = null, $can_edit_messages = null, $can_pin_messages = null, $can_manage_topics = null): TelegramResponse
    {
        return parent::promoteChatMember(Helpers::array_filter(['chat_id' => $chat_id, 'user_id' => $user_id, 'is_anonymous' => $is_anonymous, 'can_manage_chat' => $can_manage_chat, 'can_delete_messages' => $can_delete_messages, 'can_manage_video_chats' => $can_manage_video_chats, 'can_restrict_members' => $can_restrict_members, 'can_promote_members' => $can_promote_members, 'can_change_info' => $can_change_info, 'can_invite_users' => $can_invite_users, 'can_post_stories' => $can_post_stories, 'can_edit_stories' => $can_edit_stories, 'can_delete_stories' => $can_delete_stories, 'can_post_messages' => $can_post_messages, 'can_edit_messages' => $can_edit_messages, 'can_pin_messages' => $can_pin_messages, 'can_manage_topics' => $can_manage_topics]));
    }

    /**
     * Use this method to set a custom title for an administrator in a supergroup promoted by the bot.
     * Returns True on success.
     */
    public function setChatAdministratorCustomTitle($chat_id, $user_id, $custom_title): TelegramResponse
    {
        return parent::setChatAdministratorCustomTitle(Helpers::array_filter(['chat_id' => $chat_id, 'user_id' => $user_id, 'custom_title' => $custom_title]));
    }

    /**
     * Use this method to ban a channel chat in a supergroup or a channel.
     * Until the chat is unbanned, the owner of the banned chat won't be able to send messages on behalf of any of their channels.
     * The bot must be an administrator in the supergroup or channel for this to work and must have the appropriate administrator rights.
     * Returns True on success.
     */
    public function banChatSenderChat($chat_id, $sender_chat_id): TelegramResponse
    {
        return parent::banChatSenderChat(Helpers::array_filter(['chat_id' => $chat_id, 'sender_chat_id' => $sender_chat_id]));
    }

    /**
     * Use this method to unban a previously banned channel chat in a supergroup or channel.
     * The bot must be an administrator for this to work and must have the appropriate administrator rights.
     * Returns True on success.
     */
    public function unbanChatSenderChat($chat_id, $sender_chat_id): TelegramResponse
    {
        return parent::unbanChatSenderChat(Helpers::array_filter(['chat_id' => $chat_id, 'sender_chat_id' => $sender_chat_id]));
    }

    /**
     * Use this method to set default chat permissions for all members.
     * The bot must be an administrator in the group or a supergroup for this to work and must have the can_restrict_members administrator rights.
     * Returns True on success.
     */
    public function setChatPermissions($chat_id, $permissions, $use_independent_chat_permissions = null): TelegramResponse
    {
        return parent::setChatPermissions(Helpers::array_filter(['chat_id' => $chat_id, 'permissions' => $permissions, 'use_independent_chat_permissions' => $use_independent_chat_permissions]));
    }

    /**
     * Use this method to generate a new primary invite link for a chat; any previously generated primary link is revoked.
     * The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights.
     * Returns the new invite link as String on success.
     */
    public function exportChatInviteLink($chat_id): TelegramResponse
    {
        return parent::exportChatInviteLink(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to create an additional invite link for a chat.
     * The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights.
     * The link can be revoked using the method revokeChatInviteLink.
     * Returns the new invite link as ChatInviteLink object.
     */
    public function createChatInviteLink($chat_id, $name = null, $expire_date = null, $member_limit = null, $creates_join_request = null): TelegramResponse
    {
        return parent::createChatInviteLink(Helpers::array_filter(['chat_id' => $chat_id, 'name' => $name, 'expire_date' => $expire_date, 'member_limit' => $member_limit, 'creates_join_request' => $creates_join_request]));
    }

    /**
     * Use this method to edit a non-primary invite link created by the bot.
     * The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights.
     * Returns the edited invite link as a ChatInviteLink object.
     */
    public function editChatInviteLink($chat_id, $invite_link, $name = null, $expire_date = null, $member_limit = null, $creates_join_request = null): TelegramResponse
    {
        return parent::editChatInviteLink(Helpers::array_filter(['chat_id' => $chat_id, 'invite_link' => $invite_link, 'name' => $name, 'expire_date' => $expire_date, 'member_limit' => $member_limit, 'creates_join_request' => $creates_join_request]));
    }

    /**
     * Use this method to create a subscription invite link for a channel chat.
     * The bot must have the can_invite_users administrator rights.
     * The link can be edited using the method editChatSubscriptionInviteLink or revoked using the method revokeChatInviteLink.
     * Returns the new invite link as a ChatInviteLink object.
     */
    public function createChatSubscriptionInviteLink($chat_id, $subscription_period, $subscription_price, $name = null): TelegramResponse
    {
        return parent::createChatSubscriptionInviteLink(Helpers::array_filter(['chat_id' => $chat_id, 'subscription_period' => $subscription_period, 'subscription_price' => $subscription_price, 'name' => $name]));
    }

    /**
     * Use this method to edit a subscription invite link created by the bot.
     * The bot must have the can_invite_users administrator rights.
     * Returns the edited invite link as a ChatInviteLink object.
     */
    public function editChatSubscriptionInviteLink($chat_id, $invite_link, $name = null): TelegramResponse
    {
        return parent::editChatSubscriptionInviteLink(Helpers::array_filter(['chat_id' => $chat_id, 'invite_link' => $invite_link, 'name' => $name]));
    }

    /**
     * Use this method to revoke an invite link created by the bot.
     * If the primary link is revoked, a new link is automatically generated.
     * The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights.
     * Returns the revoked invite link as ChatInviteLink object.
     */
    public function revokeChatInviteLink($chat_id, $invite_link): TelegramResponse
    {
        return parent::revokeChatInviteLink(Helpers::array_filter(['chat_id' => $chat_id, 'invite_link' => $invite_link]));
    }

    /**
     * Use this method to approve a chat join request.
     * The bot must be an administrator in the chat for this to work and must have the can_invite_users administrator right.
     * Returns True on success.
     */
    public function approveChatJoinRequest($chat_id, $user_id): TelegramResponse
    {
        return parent::approveChatJoinRequest(Helpers::array_filter(['chat_id' => $chat_id, 'user_id' => $user_id]));
    }

    /**
     * Use this method to decline a chat join request.
     * The bot must be an administrator in the chat for this to work and must have the can_invite_users administrator right.
     * Returns True on success.
     */
    public function declineChatJoinRequest($chat_id, $user_id): TelegramResponse
    {
        return parent::declineChatJoinRequest(Helpers::array_filter(['chat_id' => $chat_id, 'user_id' => $user_id]));
    }

    /**
     * Use this method to set a new profile photo for the chat.
     * Photos can't be changed for private chats.
     * The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights.
     * Returns True on success.
     */
    public function setChatPhoto($chat_id, $photo): TelegramResponse
    {
        return parent::setChatPhoto(Helpers::array_filter(['chat_id' => $chat_id, 'photo' => $photo]));
    }

    /**
     * Use this method to delete a chat photo.
     * Photos can't be changed for private chats.
     * The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights.
     * Returns True on success.
     */
    public function deleteChatPhoto($chat_id): TelegramResponse
    {
        return parent::deleteChatPhoto(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to change the title of a chat.
     * Titles can't be changed for private chats.
     * The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights.
     * Returns True on success.
     */
    public function setChatTitle($chat_id, $title): TelegramResponse
    {
        return parent::setChatTitle(Helpers::array_filter(['chat_id' => $chat_id, 'title' => $title]));
    }

    /**
     * Use this method to change the description of a group, a supergroup or a channel.
     * The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights.
     * Returns True on success.
     */
    public function setChatDescription($chat_id, $description = null): TelegramResponse
    {
        return parent::setChatDescription(Helpers::array_filter(['chat_id' => $chat_id, 'description' => $description]));
    }

    /**
     * Use this method to add a message to the list of pinned messages in a chat.
     * If the chat is not a private chat, the bot must be an administrator in the chat for this to work and must have the 'can_pin_messages' administrator right in a supergroup or 'can_edit_messages' administrator right in a channel.
     * Returns True on success.
     */
    public function pinChatMessage($chat_id, $message_id, $business_connection_id = null, $disable_notification = null): TelegramResponse
    {
        return parent::pinChatMessage(Helpers::array_filter(['chat_id' => $chat_id, 'message_id' => $message_id, 'business_connection_id' => $business_connection_id, 'disable_notification' => $disable_notification]));
    }

    /**
     * Use this method to remove a message from the list of pinned messages in a chat.
     * If the chat is not a private chat, the bot must be an administrator in the chat for this to work and must have the 'can_pin_messages' administrator right in a supergroup or 'can_edit_messages' administrator right in a channel.
     * Returns True on success.
     */
    public function unpinChatMessage($chat_id, $business_connection_id = null, $message_id = null): TelegramResponse
    {
        return parent::unpinChatMessage(Helpers::array_filter(['chat_id' => $chat_id, 'business_connection_id' => $business_connection_id, 'message_id' => $message_id]));
    }

    /**
     * Use this method to clear the list of pinned messages in a chat.
     * If the chat is not a private chat, the bot must be an administrator in the chat for this to work and must have the 'can_pin_messages' administrator right in a supergroup or 'can_edit_messages' administrator right in a channel.
     * Returns True on success.
     */
    public function unpinAllChatMessages($chat_id): TelegramResponse
    {
        return parent::unpinAllChatMessages(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method for your bot to leave a group, supergroup or channel.
     * Returns True on success.
     */
    public function leaveChat($chat_id): TelegramResponse
    {
        return parent::leaveChat(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to get up-to-date information about the chat.
     * Returns a ChatFullInfo object on success.
     */
    public function getChat($chat_id): TelegramResponse
    {
        return parent::getChat(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to get a list of administrators in a chat, which aren't bots.
     * Returns an Array of ChatMember objects.
     */
    public function getChatAdministrators($chat_id): TelegramResponse
    {
        return parent::getChatAdministrators(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to get the number of members in a chat.
     * Returns Int on success.
     */
    public function getChatMemberCount($chat_id): TelegramResponse
    {
        return parent::getChatMemberCount(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to get information about a member of a chat.
     * The method is only guaranteed to work for other users if the bot is an administrator in the chat.
     * Returns a ChatMember object on success.
     */
    public function getChatMember($chat_id, $user_id): TelegramResponse
    {
        return parent::getChatMember(Helpers::array_filter(['chat_id' => $chat_id, 'user_id' => $user_id]));
    }

    /**
     * Use this method to set a new group sticker set for a supergroup.
     * The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights.
     * Use the field can_set_sticker_set optionally returned in getChat requests to check if the bot can use this method.
     * Returns True on success.
     */
    public function setChatStickerSet($chat_id, $sticker_set_name): TelegramResponse
    {
        return parent::setChatStickerSet(Helpers::array_filter(['chat_id' => $chat_id, 'sticker_set_name' => $sticker_set_name]));
    }

    /**
     * Use this method to delete a group sticker set from a supergroup.
     * The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights.
     * Use the field can_set_sticker_set optionally returned in getChat requests to check if the bot can use this method.
     * Returns True on success.
     */
    public function deleteChatStickerSet($chat_id): TelegramResponse
    {
        return parent::deleteChatStickerSet(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to get custom emoji stickers, which can be used as a forum topic icon by any user.
     * Requires no parameters.
     * Returns an Array of Sticker objects.
     */
    public function getForumTopicIconStickers(): TelegramResponse
    {
        return parent::getForumTopicIconStickers(Helpers::array_filter([]));
    }

    /**
     * Use this method to create a topic in a forum supergroup chat.
     * The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights.
     * Returns information about the created topic as a ForumTopic object.
     */
    public function createForumTopic($chat_id, $name, $icon_color = null, $icon_custom_emoji_id = null): TelegramResponse
    {
        return parent::createForumTopic(Helpers::array_filter(['chat_id' => $chat_id, 'name' => $name, 'icon_color' => $icon_color, 'icon_custom_emoji_id' => $icon_custom_emoji_id]));
    }

    /**
     * Use this method to edit name and icon of a topic in a forum supergroup chat.
     * The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights, unless it is the creator of the topic.
     * Returns True on success.
     */
    public function editForumTopic($chat_id, $message_thread_id, $name = null, $icon_custom_emoji_id = null): TelegramResponse
    {
        return parent::editForumTopic(Helpers::array_filter(['chat_id' => $chat_id, 'message_thread_id' => $message_thread_id, 'name' => $name, 'icon_custom_emoji_id' => $icon_custom_emoji_id]));
    }

    /**
     * Use this method to close an open topic in a forum supergroup chat.
     * The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights, unless it is the creator of the topic.
     * Returns True on success.
     */
    public function closeForumTopic($chat_id, $message_thread_id): TelegramResponse
    {
        return parent::closeForumTopic(Helpers::array_filter(['chat_id' => $chat_id, 'message_thread_id' => $message_thread_id]));
    }

    /**
     * Use this method to reopen a closed topic in a forum supergroup chat.
     * The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights, unless it is the creator of the topic.
     * Returns True on success.
     */
    public function reopenForumTopic($chat_id, $message_thread_id): TelegramResponse
    {
        return parent::reopenForumTopic(Helpers::array_filter(['chat_id' => $chat_id, 'message_thread_id' => $message_thread_id]));
    }

    /**
     * Use this method to delete a forum topic along with all its messages in a forum supergroup chat.
     * The bot must be an administrator in the chat for this to work and must have the can_delete_messages administrator rights.
     * Returns True on success.
     */
    public function deleteForumTopic($chat_id, $message_thread_id): TelegramResponse
    {
        return parent::deleteForumTopic(Helpers::array_filter(['chat_id' => $chat_id, 'message_thread_id' => $message_thread_id]));
    }

    /**
     * Use this method to clear the list of pinned messages in a forum topic.
     * The bot must be an administrator in the chat for this to work and must have the can_pin_messages administrator right in the supergroup.
     * Returns True on success.
     */
    public function unpinAllForumTopicMessages($chat_id, $message_thread_id): TelegramResponse
    {
        return parent::unpinAllForumTopicMessages(Helpers::array_filter(['chat_id' => $chat_id, 'message_thread_id' => $message_thread_id]));
    }

    /**
     * Use this method to edit the name of the 'General' topic in a forum supergroup chat.
     * The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights.
     * Returns True on success.
     */
    public function editGeneralForumTopic($chat_id, $name): TelegramResponse
    {
        return parent::editGeneralForumTopic(Helpers::array_filter(['chat_id' => $chat_id, 'name' => $name]));
    }

    /**
     * Use this method to close an open 'General' topic in a forum supergroup chat.
     * The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights.
     * Returns True on success.
     */
    public function closeGeneralForumTopic($chat_id): TelegramResponse
    {
        return parent::closeGeneralForumTopic(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to reopen a closed 'General' topic in a forum supergroup chat.
     * The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights.
     * The topic will be automatically unhidden if it was hidden.
     * Returns True on success.
     */
    public function reopenGeneralForumTopic($chat_id): TelegramResponse
    {
        return parent::reopenGeneralForumTopic(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to hide the 'General' topic in a forum supergroup chat.
     * The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights.
     * The topic will be automatically closed if it was open.
     * Returns True on success.
     */
    public function hideGeneralForumTopic($chat_id): TelegramResponse
    {
        return parent::hideGeneralForumTopic(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to unhide the 'General' topic in a forum supergroup chat.
     * The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights.
     * Returns True on success.
     */
    public function unhideGeneralForumTopic($chat_id): TelegramResponse
    {
        return parent::unhideGeneralForumTopic(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to clear the list of pinned messages in a General forum topic.
     * The bot must be an administrator in the chat for this to work and must have the can_pin_messages administrator right in the supergroup.
     * Returns True on success.
     */
    public function unpinAllGeneralForumTopicMessages($chat_id): TelegramResponse
    {
        return parent::unpinAllGeneralForumTopicMessages(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to send answers to callback queries sent from inline keyboards.
     * The answer will be displayed to the user as a notification at the top of the chat screen or as an alert.
     * On success, True is returned.
     */
    public function answerCallbackQuery(): TelegramResponse
    {
        return parent::answerCallbackQuery(Helpers::array_filter([]));
    }

    /**
     * Use this method to get the list of boosts added to a chat by a user.
     * Requires administrator rights in the chat.
     * Returns a UserChatBoosts object.
     */
    public function getUserChatBoosts($chat_id, $user_id): TelegramResponse
    {
        return parent::getUserChatBoosts(Helpers::array_filter(['chat_id' => $chat_id, 'user_id' => $user_id]));
    }

    /**
     * Use this method to get information about the connection of the bot with a business account.
     * Returns a BusinessConnection object on success.
     */
    public function getBusinessConnection($business_connection_id): TelegramResponse
    {
        return parent::getBusinessConnection(Helpers::array_filter(['business_connection_id' => $business_connection_id]));
    }

    /**
     * Use this method to change the list of the bot's commands.
     * See this manual for more details about bot commands.
     * Returns True on success.
     */
    public function setMyCommands($commands, $scope = null, $language_code = null): TelegramResponse
    {
        return parent::setMyCommands(Helpers::array_filter(['commands' => $commands, 'scope' => $scope, 'language_code' => $language_code]));
    }

    /**
     * Use this method to delete the list of the bot's commands for the given scope and user language.
     * After deletion, higher level commands will be shown to affected users.
     * Returns True on success.
     */
    public function deleteMyCommands($scope = null, $language_code = null): TelegramResponse
    {
        return parent::deleteMyCommands(Helpers::array_filter(['scope' => $scope, 'language_code' => $language_code]));
    }

    /**
     * Use this method to get the current list of the bot's commands for the given scope and user language.
     * Returns an Array of BotCommand objects.
     * If commands aren't set, an empty list is returned.
     */
    public function getMyCommands($scope = null, $language_code = null): TelegramResponse
    {
        return parent::getMyCommands(Helpers::array_filter(['scope' => $scope, 'language_code' => $language_code]));
    }

    /**
     * Use this method to change the bot's name.
     * Returns True on success.
     */
    public function setMyName($name = null, $language_code = null): TelegramResponse
    {
        return parent::setMyName(Helpers::array_filter(['name' => $name, 'language_code' => $language_code]));
    }

    /**
     * Use this method to get the current bot name for the given user language.
     * Returns BotName on success.
     */
    public function getMyName($language_code = null): TelegramResponse
    {
        return parent::getMyName(Helpers::array_filter(['language_code' => $language_code]));
    }

    /**
     * Use this method to change the bot's description, which is shown in the chat with the bot if the chat is empty.
     * Returns True on success.
     */
    public function setMyDescription($description = null, $language_code = null): TelegramResponse
    {
        return parent::setMyDescription(Helpers::array_filter(['description' => $description, 'language_code' => $language_code]));
    }

    /**
     * Use this method to get the current bot description for the given user language.
     * Returns BotDescription on success.
     */
    public function getMyDescription($language_code = null): TelegramResponse
    {
        return parent::getMyDescription(Helpers::array_filter(['language_code' => $language_code]));
    }

    /**
     * Use this method to change the bot's short description, which is shown on the bot's profile page and is sent together with the link when users share the bot.
     * Returns True on success.
     */
    public function setMyShortDescription($short_description = null, $language_code = null): TelegramResponse
    {
        return parent::setMyShortDescription(Helpers::array_filter(['short_description' => $short_description, 'language_code' => $language_code]));
    }

    /**
     * Use this method to get the current bot short description for the given user language.
     * Returns BotShortDescription on success.
     */
    public function getMyShortDescription($language_code = null): TelegramResponse
    {
        return parent::getMyShortDescription(Helpers::array_filter(['language_code' => $language_code]));
    }

    /**
     * Use this method to change the bot's menu button in a private chat, or the default menu button.
     * Returns True on success.
     */
    public function setChatMenuButton($chat_id = null, $menu_button = null): TelegramResponse
    {
        return parent::setChatMenuButton(Helpers::array_filter(['chat_id' => $chat_id, 'menu_button' => $menu_button]));
    }

    /**
     * Use this method to get the current value of the bot's menu button in a private chat, or the default menu button.
     * Returns MenuButton on success.
     */
    public function getChatMenuButton($chat_id = null): TelegramResponse
    {
        return parent::getChatMenuButton(Helpers::array_filter(['chat_id' => $chat_id]));
    }

    /**
     * Use this method to change the default administrator rights requested by the bot when it's added as an administrator to groups or channels.
     * These rights will be suggested to users, but they are free to modify the list before adding the bot.
     * Returns True on success.
     */
    public function setMyDefaultAdministratorRights($rights = null, $for_channels = null): TelegramResponse
    {
        return parent::setMyDefaultAdministratorRights(Helpers::array_filter(['rights' => $rights, 'for_channels' => $for_channels]));
    }

    /**
     * Use this method to get the current default administrator rights of the bot.
     * Returns ChatAdministratorRights on success.
     */
    public function getMyDefaultAdministratorRights($for_channels = null): TelegramResponse
    {
        return parent::getMyDefaultAdministratorRights(Helpers::array_filter(['for_channels' => $for_channels]));
    }

    /**
     * Use this method to edit text and game messages.
     * On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned.
     * Note that business messages that were not sent by the bot and do not contain an inline keyboard can only be edited within 48 hours from the time they were sent.
     */
    public function editMessageText($text, $business_connection_id = null, $chat_id = null, $message_id = null, $inline_message_id = null, $parse_mode = null, $entities = null, $link_preview_options = null, $reply_markup = null): TelegramResponse
    {
        return parent::editMessageText(Helpers::array_filter(['text' => $text, 'business_connection_id' => $business_connection_id, 'chat_id' => $chat_id, 'message_id' => $message_id, 'inline_message_id' => $inline_message_id, 'parse_mode' => $parse_mode, 'entities' => $entities, 'link_preview_options' => $link_preview_options, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to edit captions of messages.
     * On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned.
     * Note that business messages that were not sent by the bot and do not contain an inline keyboard can only be edited within 48 hours from the time they were sent.
     */
    public function editMessageCaption($business_connection_id = null, $chat_id = null, $message_id = null, $inline_message_id = null, $caption = null, $parse_mode = null, $caption_entities = null, $show_caption_above_media = null, $reply_markup = null): TelegramResponse
    {
        return parent::editMessageCaption(Helpers::array_filter(['business_connection_id' => $business_connection_id, 'chat_id' => $chat_id, 'message_id' => $message_id, 'inline_message_id' => $inline_message_id, 'caption' => $caption, 'parse_mode' => $parse_mode, 'caption_entities' => $caption_entities, 'show_caption_above_media' => $show_caption_above_media, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to edit animation, audio, document, photo, or video messages, or to add media to text messages.
     * If a message is part of a message album, then it can be edited only to an audio for audio albums, only to a document for document albums and to a photo or a video otherwise.
     * When an inline message is edited, a new file can't be uploaded; use a previously uploaded file via its file_id or specify a URL.
     * On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned.
     * Note that business messages that were not sent by the bot and do not contain an inline keyboard can only be edited within 48 hours from the time they were sent.
     */
    public function editMessageMedia($media, $business_connection_id = null, $chat_id = null, $message_id = null, $inline_message_id = null, $reply_markup = null): TelegramResponse
    {
        return parent::editMessageMedia(Helpers::array_filter(['media' => $media, 'business_connection_id' => $business_connection_id, 'chat_id' => $chat_id, 'message_id' => $message_id, 'inline_message_id' => $inline_message_id, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to edit live location messages.
     * A location can be edited until its live_period expires or editing is explicitly disabled by a call to stopMessageLiveLocation.
     * On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned.
     */
    public function editMessageLiveLocation($latitude, $longitude, $business_connection_id = null, $chat_id = null, $message_id = null, $inline_message_id = null, $live_period = null, $horizontal_accuracy = null, $heading = null, $proximity_alert_radius = null, $reply_markup = null): TelegramResponse
    {
        return parent::editMessageLiveLocation(Helpers::array_filter(['latitude' => $latitude, 'longitude' => $longitude, 'business_connection_id' => $business_connection_id, 'chat_id' => $chat_id, 'message_id' => $message_id, 'inline_message_id' => $inline_message_id, 'live_period' => $live_period, 'horizontal_accuracy' => $horizontal_accuracy, 'heading' => $heading, 'proximity_alert_radius' => $proximity_alert_radius, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to stop updating a live location message before live_period expires.
     * On success, if the message is not an inline message, the edited Message is returned, otherwise True is returned.
     */
    public function stopMessageLiveLocation($business_connection_id = null, $chat_id = null, $message_id = null, $inline_message_id = null, $reply_markup = null): TelegramResponse
    {
        return parent::stopMessageLiveLocation(Helpers::array_filter(['business_connection_id' => $business_connection_id, 'chat_id' => $chat_id, 'message_id' => $message_id, 'inline_message_id' => $inline_message_id, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to edit only the reply markup of messages.
     * On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned.
     * Note that business messages that were not sent by the bot and do not contain an inline keyboard can only be edited within 48 hours from the time they were sent.
     */
    public function editMessageReplyMarkup($business_connection_id = null, $chat_id = null, $message_id = null, $inline_message_id = null, $reply_markup = null): TelegramResponse
    {
        return parent::editMessageReplyMarkup(Helpers::array_filter(['business_connection_id' => $business_connection_id, 'chat_id' => $chat_id, 'message_id' => $message_id, 'inline_message_id' => $inline_message_id, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to stop a poll which was sent by the bot.
     * On success, the stopped Poll is returned.
     */
    public function stopPoll($chat_id, $message_id, $business_connection_id = null, $reply_markup = null): TelegramResponse
    {
        return parent::stopPoll(Helpers::array_filter(['chat_id' => $chat_id, 'message_id' => $message_id, 'business_connection_id' => $business_connection_id, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to delete a message, including service messages, with the following limitations:- A message can only be deleted if it was sent less than 48 hours ago.- Service messages about a supergroup, channel, or forum topic creation can't be deleted.- A dice message in a private chat can only be deleted if it was sent more than 24 hours ago.- Bots can delete outgoing messages in private chats, groups, and supergroups.- Bots can delete incoming messages in private chats.- Bots granted can_post_messages permissions can delete outgoing messages in channels.- If the bot is an administrator of a group, it can delete any message there.- If the bot has can_delete_messages permission in a supergroup or a channel, it can delete any message there.Returns True on success.
     */
    public function deleteMessage($chat_id, $message_id): TelegramResponse
    {
        return parent::deleteMessage(Helpers::array_filter(['chat_id' => $chat_id, 'message_id' => $message_id]));
    }

    /**
     * Use this method to delete multiple messages simultaneously.
     * If some of the specified messages can't be found, they are skipped.
     * Returns True on success.
     */
    public function deleteMessages($chat_id, $message_ids): TelegramResponse
    {
        return parent::deleteMessages(Helpers::array_filter(['chat_id' => $chat_id, 'message_ids' => $message_ids]));
    }

    /**
     * Use this method to send static .WEBP, animated .TGS, or video .WEBM stickers.
     * On success, the sent Message is returned.
     */
    public function sendSticker($chat_id, $sticker, $business_connection_id = null, $message_thread_id = null, $emoji = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendSticker(Helpers::array_filter(['chat_id' => $chat_id, 'sticker' => $sticker, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'emoji' => $emoji, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to get a sticker set.
     * On success, a StickerSet object is returned.
     */
    public function getStickerSet($name): TelegramResponse
    {
        return parent::getStickerSet(Helpers::array_filter(['name' => $name]));
    }

    /**
     * Use this method to get information about custom emoji stickers by their identifiers.
     * Returns an Array of Sticker objects.
     */
    public function getCustomEmojiStickers($custom_emoji_ids): TelegramResponse
    {
        return parent::getCustomEmojiStickers(Helpers::array_filter(['custom_emoji_ids' => $custom_emoji_ids]));
    }

    /**
     * Use this method to upload a file with a sticker for later use in the createNewStickerSet, addStickerToSet, or replaceStickerInSet methods (the file can be used multiple times).
     * Returns the uploaded File on success.
     */
    public function uploadStickerFile($user_id, $sticker, $sticker_format): TelegramResponse
    {
        return parent::uploadStickerFile(Helpers::array_filter(['user_id' => $user_id, 'sticker' => $sticker, 'sticker_format' => $sticker_format]));
    }

    /**
     * Use this method to create a new sticker set owned by a user.
     * The bot will be able to edit the sticker set thus created.
     * Returns True on success.
     */
    public function createNewStickerSet($user_id, $name, $title, $stickers, $sticker_type = null, $needs_repainting = null): TelegramResponse
    {
        return parent::createNewStickerSet(Helpers::array_filter(['user_id' => $user_id, 'name' => $name, 'title' => $title, 'stickers' => $stickers, 'sticker_type' => $sticker_type, 'needs_repainting' => $needs_repainting]));
    }

    /**
     * Use this method to add a new sticker to a set created by the bot.
     * Emoji sticker sets can have up to 200 stickers.
     * Other sticker sets can have up to 120 stickers.
     * Returns True on success.
     */
    public function addStickerToSet($user_id, $name, $sticker): TelegramResponse
    {
        return parent::addStickerToSet(Helpers::array_filter(['user_id' => $user_id, 'name' => $name, 'sticker' => $sticker]));
    }

    /**
     * Use this method to move a sticker in a set created by the bot to a specific position.
     * Returns True on success.
     */
    public function setStickerPositionInSet($sticker, $position): TelegramResponse
    {
        return parent::setStickerPositionInSet(Helpers::array_filter(['sticker' => $sticker, 'position' => $position]));
    }

    /**
     * Use this method to delete a sticker from a set created by the bot.
     * Returns True on success.
     */
    public function deleteStickerFromSet($sticker): TelegramResponse
    {
        return parent::deleteStickerFromSet(Helpers::array_filter(['sticker' => $sticker]));
    }

    /**
     * Use this method to replace an existing sticker in a sticker set with a new one.
     * The method is equivalent to calling deleteStickerFromSet, then addStickerToSet, then setStickerPositionInSet.
     * Returns True on success.
     */
    public function replaceStickerInSet($user_id, $name, $old_sticker, $sticker): TelegramResponse
    {
        return parent::replaceStickerInSet(Helpers::array_filter(['user_id' => $user_id, 'name' => $name, 'old_sticker' => $old_sticker, 'sticker' => $sticker]));
    }

    /**
     * Use this method to change the list of emoji assigned to a regular or custom emoji sticker.
     * The sticker must belong to a sticker set created by the bot.
     * Returns True on success.
     */
    public function setStickerEmojiList($sticker, $emoji_list): TelegramResponse
    {
        return parent::setStickerEmojiList(Helpers::array_filter(['sticker' => $sticker, 'emoji_list' => $emoji_list]));
    }

    /**
     * Use this method to change search keywords assigned to a regular or custom emoji sticker.
     * The sticker must belong to a sticker set created by the bot.
     * Returns True on success.
     */
    public function setStickerKeywords($sticker, $keywords = null): TelegramResponse
    {
        return parent::setStickerKeywords(Helpers::array_filter(['sticker' => $sticker, 'keywords' => $keywords]));
    }

    /**
     * Use this method to change the mask position of a mask sticker.
     * The sticker must belong to a sticker set that was created by the bot.
     * Returns True on success.
     */
    public function setStickerMaskPosition($sticker, $mask_position = null): TelegramResponse
    {
        return parent::setStickerMaskPosition(Helpers::array_filter(['sticker' => $sticker, 'mask_position' => $mask_position]));
    }

    /**
     * Use this method to set the title of a created sticker set.
     * Returns True on success.
     */
    public function setStickerSetTitle($name, $title): TelegramResponse
    {
        return parent::setStickerSetTitle(Helpers::array_filter(['name' => $name, 'title' => $title]));
    }

    /**
     * Use this method to set the thumbnail of a regular or mask sticker set.
     * The format of the thumbnail file must match the format of the stickers in the set.
     * Returns True on success.
     */
    public function setStickerSetThumbnail($name, $user_id, $format, $thumbnail = null): TelegramResponse
    {
        return parent::setStickerSetThumbnail(Helpers::array_filter(['name' => $name, 'user_id' => $user_id, 'format' => $format, 'thumbnail' => $thumbnail]));
    }

    /**
     * Use this method to set the thumbnail of a custom emoji sticker set.
     * Returns True on success.
     */
    public function setCustomEmojiStickerSetThumbnail($name, $custom_emoji_id = null): TelegramResponse
    {
        return parent::setCustomEmojiStickerSetThumbnail(Helpers::array_filter(['name' => $name, 'custom_emoji_id' => $custom_emoji_id]));
    }

    /**
     * Use this method to delete a sticker set that was created by the bot.
     * Returns True on success.
     */
    public function deleteStickerSet($name): TelegramResponse
    {
        return parent::deleteStickerSet(Helpers::array_filter(['name' => $name]));
    }

    /**
     * Use this method to send answers to an inline query.
     * On success, True is returned.No more than 50 results per query are allowed.
     */
    public function answerInlineQuery($inline_query_id, $results, $cache_time = null, $is_personal = null, $next_offset = null, $button = null): TelegramResponse
    {
        return parent::answerInlineQuery(Helpers::array_filter(['inline_query_id' => $inline_query_id, 'results' => $results, 'cache_time' => $cache_time, 'is_personal' => $is_personal, 'next_offset' => $next_offset, 'button' => $button]));
    }

    /**
     * Use this method to set the result of an interaction with a Web App and send a corresponding message on behalf of the user to the chat from which the query originated.
     * On success, a SentWebAppMessage object is returned.
     */
    public function answerWebAppQuery($web_app_query_id, $result): TelegramResponse
    {
        return parent::answerWebAppQuery(Helpers::array_filter(['web_app_query_id' => $web_app_query_id, 'result' => $result]));
    }

    /**
     * Use this method to send invoices.
     * On success, the sent Message is returned.
     */
    public function sendInvoice($chat_id, $title, $description, $payload, $currency, $prices, $message_thread_id = null, $provider_token = null, $max_tip_amount = null, $suggested_tip_amounts = null, $start_parameter = null, $provider_data = null, $photo_url = null, $photo_size = null, $photo_width = null, $photo_height = null, $need_name = null, $need_phone_number = null, $need_email = null, $need_shipping_address = null, $send_phone_number_to_provider = null, $send_email_to_provider = null, $is_flexible = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendInvoice(Helpers::array_filter(['chat_id' => $chat_id, 'title' => $title, 'description' => $description, 'payload' => $payload, 'currency' => $currency, 'prices' => $prices, 'message_thread_id' => $message_thread_id, 'provider_token' => $provider_token, 'max_tip_amount' => $max_tip_amount, 'suggested_tip_amounts' => $suggested_tip_amounts, 'start_parameter' => $start_parameter, 'provider_data' => $provider_data, 'photo_url' => $photo_url, 'photo_size' => $photo_size, 'photo_width' => $photo_width, 'photo_height' => $photo_height, 'need_name' => $need_name, 'need_phone_number' => $need_phone_number, 'need_email' => $need_email, 'need_shipping_address' => $need_shipping_address, 'send_phone_number_to_provider' => $send_phone_number_to_provider, 'send_email_to_provider' => $send_email_to_provider, 'is_flexible' => $is_flexible, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to create a link for an invoice.
     * Returns the created invoice link as String on success.
     */
    public function createInvoiceLink($title, $description, $payload, $currency, $prices, $provider_token = null, $max_tip_amount = null, $suggested_tip_amounts = null, $provider_data = null, $photo_url = null, $photo_size = null, $photo_width = null, $photo_height = null, $need_name = null, $need_phone_number = null, $need_email = null, $need_shipping_address = null, $send_phone_number_to_provider = null, $send_email_to_provider = null, $is_flexible = null): TelegramResponse
    {
        return parent::createInvoiceLink(Helpers::array_filter(['title' => $title, 'description' => $description, 'payload' => $payload, 'currency' => $currency, 'prices' => $prices, 'provider_token' => $provider_token, 'max_tip_amount' => $max_tip_amount, 'suggested_tip_amounts' => $suggested_tip_amounts, 'provider_data' => $provider_data, 'photo_url' => $photo_url, 'photo_size' => $photo_size, 'photo_width' => $photo_width, 'photo_height' => $photo_height, 'need_name' => $need_name, 'need_phone_number' => $need_phone_number, 'need_email' => $need_email, 'need_shipping_address' => $need_shipping_address, 'send_phone_number_to_provider' => $send_phone_number_to_provider, 'send_email_to_provider' => $send_email_to_provider, 'is_flexible' => $is_flexible]));
    }

    /**
     * If you sent an invoice requesting a shipping address and the parameter is_flexible was specified, the Bot API will send an Update with a shipping_query field to the bot.
     * Use this method to reply to shipping queries.
     * On success, True is returned.
     */
    public function answerShippingQuery($shipping_query_id, $ok, $shipping_options = null, $error_message = null): TelegramResponse
    {
        return parent::answerShippingQuery(Helpers::array_filter(['shipping_query_id' => $shipping_query_id, 'ok' => $ok, 'shipping_options' => $shipping_options, 'error_message' => $error_message]));
    }

    /**
     * Once the user has confirmed their payment and shipping details, the Bot API sends the final confirmation in the form of an Update with the field pre_checkout_query.
     * Use this method to respond to such pre-checkout queries.
     * On success, True is returned.
     * Note: The Bot API must receive an answer within 10 seconds after the pre-checkout query was sent.
     */
    public function answerPreCheckoutQuery($pre_checkout_query_id, $ok, $error_message = null): TelegramResponse
    {
        return parent::answerPreCheckoutQuery(Helpers::array_filter(['pre_checkout_query_id' => $pre_checkout_query_id, 'ok' => $ok, 'error_message' => $error_message]));
    }

    /**
     * Returns the bot's Telegram Star transactions in chronological order.
     * On success, returns a StarTransactions object.
     */
    public function getStarTransactions($offset = null, $limit = null): TelegramResponse
    {
        return parent::getStarTransactions(Helpers::array_filter(['offset' => $offset, 'limit' => $limit]));
    }

    /**
     * Refunds a successful payment in Telegram Stars.
     * Returns True on success.
     */
    public function refundStarPayment($user_id, $telegram_payment_charge_id): TelegramResponse
    {
        return parent::refundStarPayment(Helpers::array_filter(['user_id' => $user_id, 'telegram_payment_charge_id' => $telegram_payment_charge_id]));
    }

    /**
     * Informs a user that some of the Telegram Passport elements they provided contains errors.
     * The user will not be able to re-submit their Passport to you until the errors are fixed (the contents of the field for which you returned the error must change).
     * Returns True on success.
     */
    public function setPassportDataErrors(): TelegramResponse
    {
        return parent::setPassportDataErrors(Helpers::array_filter([]));
    }

    /**
     * Use this method to send a game.
     * On success, the sent Message is returned.
     */
    public function sendGame($chat_id, $game_short_name, $business_connection_id = null, $message_thread_id = null, $disable_notification = null, $protect_content = null, $allow_paid_broadcast = null, $message_effect_id = null, $reply_parameters = null, $reply_markup = null): TelegramResponse
    {
        return parent::sendGame(Helpers::array_filter(['chat_id' => $chat_id, 'game_short_name' => $game_short_name, 'business_connection_id' => $business_connection_id, 'message_thread_id' => $message_thread_id, 'disable_notification' => $disable_notification, 'protect_content' => $protect_content, 'allow_paid_broadcast' => $allow_paid_broadcast, 'message_effect_id' => $message_effect_id, 'reply_parameters' => $reply_parameters, 'reply_markup' => $reply_markup]));
    }

    /**
     * Use this method to set the score of the specified user in a game message.
     * On success, if the message is not an inline message, the Message is returned, otherwise True is returned.
     * Returns an error, if the new score is not greater than the user's current score in the chat and force is False.
     */
    public function setGameScore($user_id, $score, $force = null, $disable_edit_message = null, $chat_id = null, $message_id = null, $inline_message_id = null): TelegramResponse
    {
        return parent::setGameScore(Helpers::array_filter(['user_id' => $user_id, 'score' => $score, 'force' => $force, 'disable_edit_message' => $disable_edit_message, 'chat_id' => $chat_id, 'message_id' => $message_id, 'inline_message_id' => $inline_message_id]));
    }

    /**
     * Use this method to get data for high score tables.
     * Will return the score of the specified user and several of their neighbors in a game.
     * Returns an Array of GameHighScore objects.
     */
    public function getGameHighScores(): TelegramResponse
    {
        return parent::getGameHighScores(Helpers::array_filter([]));
    }
}
